import type { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import classNames from "classnames";

const nextShiny = (mon: number) =>
  `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/shiny/${mon}.png`;

const nextNormal = (mon: number) =>
  `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/${mon}.png`;

let next = Math.round(Math.random() * 905 + 0.5);

function dex() {
  let temp = next;

  if (temp == 718) {
    return 719;
  }
  if (temp == 774) {
    return 775;
  }

  next = Math.round(Math.random() * 905 + 0.5);

  //new Image().src = nextShiny(pokeNum);

  //new Image().src = nextNormal(pokeNum);

  return temp;
}

const divName =
  "container flex flex-wrap items-center justify-start gap-5 w-40 h-40 rounded-md border-4 border-gray-900";

let pokeNum = dex();

const Home: NextPage = () => {

  const [streak, setStreak] = useState(0);

  const set = async (right: boolean) => {
    setStreak(right ? streak + 1 : 0);
    setGuess(true);
  };

  const reset = () => {
    setRand(Math.random() > 0.5);
    setGuess(false);
    pokeNum = dex();
  };

  const contain = async (right: boolean) => {
    if (!guess) {
      await set(right);
      setTimeout(() => reset(), 1000);
    }
  };

  const [guess, setGuess] = useState(false); // false = unguessed true = wrong

  const shinyClass: string = classNames(divName, {
    "bg-green-400": guess,
    "bg-slate-600": !guess,
  });

  const normalClass: string = classNames(divName, {
    "bg-red-400": guess,
    "bg-slate-600": !guess,
  });

  const showShiny = () => {
    return (
      <div className={shinyClass} onClick={() => contain(true)}>
        <img src={nextShiny(pokeNum)} className="w-full" />
      </div>
    );
  };

  const showNormal = () => {
    return (
      <div className={normalClass} onClick={() => contain(false)}>
        <img src={nextNormal(pokeNum)} className="w-full" />
      </div>
    );
  };

  const [rand, setRand] = useState(true);

  const showPokemon = () => {
    if (rand) {
      return (
        <>
          {showShiny()}
          {showNormal()}
        </>
      );
    } else {
      return (
        <>
          {showNormal()}
          {showShiny()}
        </>
      );
    }
  };

  return (
    <>
      <Head>
        <title>Shiny Guesser</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="" href="" />
      </Head>
      <main className="p-6 justify-center items-center flex flex-col bg-slate-800 w-screen h-screen gap-3">
        <div className="justify-center items-center flex gap-x-3">
          {showPokemon()}
        </div>
        <div className="p-6 justify-center items-center flex bg-slate-600 gap-x-3 min-w-fit h-5 rounded-md border-4 border-gray-900">
          Current Streak: {streak}
        </div>
      </main>
    </>
  );
};

export default Home;
